name: cgame cd workflow

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-cd:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: build web app
        run: npm build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900

      - name: Upload to S3
        run: |
          aws s3 sync ./build s3://cgame-static-ap
